Repository BT2F/queosk-front, pull requests merged in 2023-09, with the labels that each got.

#9 Feat: msw 추가 작성 및 1차 수정 진행
  mocks/handlers/commentHandler.ts
  mocks/handlers/index.ts
  mocks/handlers/queueHandler.ts
  mocks/handlers/restaurantHandler.ts
  mocks/handlers/reviewHandler.ts
  mocks/handlers/userHandler.ts
Labels: Feat, Fix

#10 hotfix: msw enabled 전에 컴포넌트들이 올라가는 사항 수정
  components/msw/MSWWraaper.tsx
  mocks/index.ts
  pages/_app.tsx
Labels: Fix

#3 Feat: 로그인 기능 및 기본 컴포넌트 구현( MSW 연동 )
  components/auth/layout/BusinessSignUpLayout.tsx
  components/auth/layout/SignLayout.tsx
  components/common/Button.tsx
  components/common/Input.tsx
  components/common/RootLayout.tsx
  components/views/auth/KAKAOCallbackView.tsx
  components/views/auth/OwnerSignInView.tsx
  components/views/auth/OwnerSignUpView.tsx
  components/views/auth/UserSignInView.tsx
  components/views/auth/UserSignUpView.tsx
  constants/auth.ts
  hooks/useAuth.ts
  hooks/useId.ts
  hooks/useUser.ts
  lib/axios.ts
  lib/fixFirstCharUpperCase.ts
  lib/regx.ts
  lib/zustand/devtools.ts
  package.json
  pages/auth/kakao/callback/index.tsx
  pages/mystore/signin/index.tsx
  pages/mystore/signup/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  types/auth.type.ts
  yarn.lock
Labels: Feat

#12 Fix: API proxy 관련 설정 변경
  lib/axios.ts
  next.config.js
Labels: Fix

#13 Hotfix: axios err 상황시 발생하는 오류 수정 코드 업로드
  lib/axios.ts
  next.config.js
Labels: Fix

#14 Feat: StoreList page 구현
  components/store_list/StoreCard.tsx
  components/store_list/StoreHeader.tsx
  components/store_list/StoreList.tsx
  components/store_list/StoreListNav.tsx
  components/store_list/StoreLocationError.tsx
  components/views/store_list/StoreListView.tsx
  constants/store_list.ts
  hooks/useLocation.ts
  hooks/useSearchParams.ts
  lib/axios.ts
  mocks/handlers/restaurantHandler.ts
  next.config.js
  package.json
  pages/store/index.tsx
  types/storeList.type.ts
  yarn.lock
Labels: Fix

#15 Fix: axios interceptor token 관련 로직 수정및 baseUrl 추가
  lib/axios.ts
  package.json
  yarn.lock
Labels: Fix

#16 Refactor: 로그인 API 스펙 변경에 따른 리펙토링 및 label 수정
  components/views/auth/OwnerSignInView.tsx
  components/views/auth/OwnerSignUpView.tsx
  components/views/auth/UserSignInView.tsx
  components/views/auth/UserSignUpView.tsx
  lib/fixInputLabel.ts
Labels: Fix, Refactor

#25 Hotfix: layout 오류 수정 및 로직 수정
  components/account/AccountHeader.tsx
  components/account/AccountLayout.tsx
  components/cart/CartMenuCard.tsx
  components/common/BackButton.tsx
  components/common/Nav.tsx
  components/store_detail/StoreDetailCard.tsx
  components/store_detail/StoreMenuHeader.tsx
  components/store_list/StoreCard.tsx
  components/store_list/StoreList.tsx
  components/views/account/Account.tsx
  components/views/cart/CartView.tsx
  components/views/store_detail/StoreDetailView.tsx
  components/views/store_list/StoreListView.tsx
  components/views/waiting/NumsOfVisitor.tsx
  components/views/waiting/Waiting.tsx
  components/views/waiting/WaitingResistration.tsx
  components/waiting/WaitingLayOut.tsx
  hooks/useAuth.ts
  hooks/useCart.ts
  lib/placeholderImgUrl.ts
  package-lock.json
  pages/index.tsx
  public/asset/logo/queosk.png
Labels: Fix, Refactor

#27 Feat: 매장요약 페이지, 다른 페이지로 이동 버튼 구현
  components/mystore_page/Header.tsx
  components/views/mystore_page/MystorePageView.tsx
  pages/mystore/index.tsx
Labels: Feat

#26 Refactor: Auth관련 로직 수정 및 미들웨어 추가
  components/auth/layout/SignLayout.tsx
  components/views/account/Account.tsx
  components/views/auth/OwnerSignInView.tsx
  components/views/auth/OwnerSignUpView.tsx
  components/views/auth/UserSignInView.tsx
  components/views/auth/UserSignUpView.tsx
  middleware.ts
Labels: Refactor

#28 Feat: 페이지 전환 애니메이션 추가
  components/common/RootLayout.tsx
  components/views/auth/KAKAOCallbackView.tsx
  pages/_app.tsx
  pages/index.tsx
Labels: Feat

#30 Hotfix: 카카오 로그인 uri 경로 수정
  hooks/useAuth.ts
Labels: Fix

#31 Hotfix: 모바일 버그로 인해 트렌지션 임시 제거
  components/common/RootLayout.tsx
Labels: Fix

#35 HotFix: type오류 수정
  components/order_move/OrderList.tsx
  components/views/order_move/OrderListMoveView.tsx
Labels: Fix

#40 Refactor: Layout 로직 변경 및 페이지 기본 로직 변경
  components/common/Layout.tsx
  components/views/auth/KAKAOCallbackView.tsx
  hooks/useAuth.ts
  pages/_app.tsx
  pages/account/index.tsx
  pages/auth/kakao/callback/index.tsx
  pages/cart/index.tsx
  pages/index.tsx
  pages/mystore/index.tsx
  pages/mystore/menu/edit/index.tsx
  pages/mystore/settlement/index.tsx
  pages/mystore/signin/index.tsx
  pages/mystore/signup/index.tsx
  pages/mystore/state/index.tsx
  pages/mystore/tables/index.tsx
  pages/mywaiting/index.tsx
  pages/payment/kakao/callback/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  pages/store/[storeId]/index.tsx
  pages/store/[storeId]/table/[tableId]/menu/index.tsx
  pages/store/[storeId]/waiting/index.tsx
  pages/store/index.tsx
Labels: Refactor

#41 Refactor: Header 통합 및 Nav css 수정
  components/common/Header.tsx
  components/common/Nav.tsx
  components/store_list/StoreList.tsx
  components/views/store_detail/StoreDetailView.tsx
  components/views/store_list/StoreListView.tsx
  pages/store/[storeId]/index.tsx
  pages/store/index.tsx
Labels: Refactor
